stages:
  data_ingestion:
    cmd: python src/RiceImgClassification/pipeline/data_ingestion_pipeline.py
    deps:
      - src/RiceImgClassification/pipeline/data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Rice_Image_Dataset
      - artifacts/data_ingestion/data.zip

  data_preparation:
    cmd: python src/RiceImgClassification/pipeline/data_preparation_pipeline.py
    deps:
      - src/RiceImgClassification/pipeline/data_preparation_pipeline.py
      - config/config.yaml
      - artifacts/data_ingestion/Rice_Image_Dataset
    outs:
      - artifacts/data_preparation/train
      - artifacts/data_preparation/test
      - artifacts/data_preparation/val

  prepare_model:
    cmd: python src/RiceImgClassification/pipeline/model_preparation_pipeline.py
    deps:
      - src/RiceImgClassification/pipeline/model_preparation_pipeline.py
      - config/config.yaml
    params:
      - weight_decay
      - input_image_size
      - learning_rate
      - epsilon
      - classes
      - epochs
      - decay_rate
    outs:
    - artifacts/prepare_model/model.h5

  training:
    cmd: python src/RiceImgClassification/pipeline/model_training_pipeline.py
    deps:
      - src/RiceImgClassification/pipeline/model_training_pipeline.py
      - config/config.yaml
      - artifacts/prepare_model/model.h5
    params:
      - epochs
    outs:
      - artifacts/training/model.h5
    metrics:
      - artifacts/training/history.json:
          cache: false

  model_evaluation:
    cmd: python src/RiceImgClassification/pipeline/model_evaluation_pipeline.py
    deps:
      - src/RiceImgClassification/pipeline/model_evaluation_pipeline.py
      - config/config.yaml
      - artifacts/training
      - artifacts/data_preparation/val
    params:
      - epochs
    outs:
      - artifacts/evaluation/graphs.png