artifacts_root: artifacts

data_ingestion:
  train_dir: artifacts/data/train
  test_dir: artifacts/data/test/test


prepare_model:
  model_path: artifacts/prepare_model/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5