artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1Qqb8zsCSUecbW8sSRzfQ37WJgEAaDPdF/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_preparation:
  root_dir: artifacts/data_preparation
  data_dir: artifacts/data_ingestion/Rice_Image_Dataset
  train_dir: artifacts/data_preparation/train
  test_dir: artifacts/data_preparation/test

prepare_model:
  root_dir: artifacts/prepare_model
  model_dir: artifacts/prepare_model/model.h5

training:
  root_dir: artifacts/training
  trained_model_dir: artifacts/training/model.h5