artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_model:
  base_model_path: artifacts/prepare_model/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5